[package]

name = "claymore"
version = "0.1.0"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[[bin]]
name = "claymore"
path = "src/main.rs"

[dependencies.blade]
path = "src/blade/"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs.git"

#[dependencies.gfx_gl]
#git = "https://github.com/gfx-rs/gfx_gl.git"
