[package]

name = "claymore"
version = "0.1.0"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[[bin]]
name = "claymore"
path = "src/main.rs"

[dependencies]
env_logger = "*"

[dependencies.claymore-scene]
path = "src/scene/"

[dependencies.claymore-load]
path = "src/load/"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs.git"
