[package]
name = "claymore-scene"
version = "0.0.1"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[lib]
name = "claymore-scene"
path = "lib.rs"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.gfx_macros]
git = "https://github.com/gfx-rs/gfx_macros"
plugin = true

[dependencies.piston-gfx_texture]
git = "https://github.com/PistonDevelopers/gfx_texture"

#[dependencies.image]
#git = "https://github.com/PistonDevelopers/image"

[dependencies]
log = "*"
rustc-serialize = "*"
