[package]
name = "claymore-scene"
version = "0.0.1"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[lib]
name = "claymore-scene"
path = "lib.rs"

[dependencies.id]
git = "https://github.com/kvark/simplecs"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.gfx_phase]
git = "https://github.com/kvark/gfx_scene"

[dependencies.gfx_scene]
git = "https://github.com/kvark/gfx_scene"

#[dependencies.image]
#git = "https://github.com/PistonDevelopers/image"
